# config.py: Automatically generated by make.
localversion = False
libexecdir = "/usr/local/libexec/"
pkgdatadir = "/usr/local/share/idjc/"
plugindir = "/usr/local/lib/python2.6/site-packages/idjc/"
avformat = 1
avcodec = 1
flacenabled = 1
oggflacenabled = 1
speexenabled = 1
version = "0.8.3_pre1"
gfext = ".png"
tipsenabled = 1
num_streamers = 6
num_encoders = 6
num_recorders = 2
enh_libshout = 1
